<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Event Summary — {{ $event->name }}</title>
    @php
        $orgEmail   = \App\Services\SettingService::get('organization.email',   '');
        $orgPhone   = \App\Services\SettingService::get('organization.phone',   '');
        $orgWebsite = \App\Services\SettingService::get('organization.website', '');
        $faviconDataUri = \App\Services\SettingService::brandingFaviconDataUri();
        $sectionLabels = [
            'event_details' => 'Event Details',
            'attendees'     => 'Attendees',
            'volunteers'    => 'Volunteers',
            'reviews'       => 'Reviews',
            'inventory'     => 'Inventory',
            'finance'       => 'Finance',
            'queue'         => 'Queue Summary',
            'evaluation'    => 'Evaluation',
        ];
    @endphp
    @if($faviconDataUri)
        <link rel="icon" href="{{ $faviconDataUri }}">
    @endif
    @vite(['resources/css/app.css'])
    <style>
        @page {
            margin: 16mm 14mm 18mm 14mm;
        }
        /* Force backgrounds/colours to render in the PDF generated by the
           browser's "Print" dialog. Without this, Chrome/Edge/Safari strip
           background colours by default — which made the cover panel and
           coloured stat tiles render as white-on-white. */
        html, body, * {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            color-adjust: exact !important;
        }
        body {
            background: #f4f5f7;
            font-family: 'Helvetica Neue', Arial, sans-serif;
        }
        .page {
            max-width: 880px;
            margin: 0 auto;
            padding: 24px;
        }

        /* Cover --------------------------------------------------------- */
        .cover {
            background: linear-gradient(135deg, #1b2b4b 0%, #243b6a 100%);
            color: white;
            border-radius: 14px;
            padding: 32px 36px;
            margin-bottom: 28px;
            position: relative;
            overflow: hidden;
        }
        .cover::after {
            content: '';
            position: absolute;
            right: -40px;
            top: -40px;
            width: 220px;
            height: 220px;
            background: rgba(255,255,255,0.06);
            border-radius: 50%;
        }
        .cover h2 {
            margin: 0;
            font-size: 11px;
            letter-spacing: 0.18em;
            text-transform: uppercase;
            color: rgba(255,255,255,0.7);
            font-weight: 600;
        }
        .cover h1 {
            margin: 6px 0 0;
            font-size: 26px;
            font-weight: 800;
            letter-spacing: -0.01em;
            line-height: 1.15;
        }
        .cover .meta {
            margin-top: 14px;
            color: rgba(255,255,255,0.85);
            font-size: 13px;
            font-weight: 500;
        }
        .cover .org-row {
            margin-top: 24px;
            padding-top: 18px;
            border-top: 1px solid rgba(255,255,255,0.18);
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 16px;
        }
        .cover .org-info {
            display: flex;
            align-items: center;
            gap: 12px;
        }
        .cover .org-info img {
            height: 40px;
            max-width: 140px;
            object-fit: contain;
            background: white;
            padding: 4px 8px;
            border-radius: 6px;
        }
        .cover .org-name {
            font-weight: 700;
            font-size: 14px;
        }
        .cover .org-contact {
            font-size: 10px;
            color: rgba(255,255,255,0.7);
            margin-top: 2px;
        }
        .cover .gen-info {
            text-align: right;
            font-size: 10px;
            color: rgba(255,255,255,0.7);
        }

        /* Table of contents -------------------------------------------- */
        .toc {
            background: white;
            border-radius: 12px;
            padding: 18px 24px;
            margin-bottom: 22px;
            border: 1px solid #e5e7eb;
        }
        .toc h3 {
            margin: 0 0 10px;
            font-size: 11px;
            font-weight: 700;
            color: #6b7280;
            text-transform: uppercase;
            letter-spacing: 0.08em;
        }
        .toc ol {
            margin: 0;
            padding-left: 20px;
            columns: 2;
            column-gap: 24px;
            font-size: 13px;
            color: #1f2937;
        }
        .toc ol li { margin: 4px 0; padding-left: 6px; }

        /* Section blocks ----------------------------------------------- */
        .section-block {
            margin-bottom: 22px;
        }
        .section-band {
            background: #1b2b4b;
            color: white;
            padding: 10px 18px;
            border-radius: 10px 10px 0 0;
            display: flex;
            align-items: center;
            gap: 10px;
            border-bottom: 3px solid #f97316;
        }
        .section-band .num {
            display: inline-block;
            width: 24px;
            height: 24px;
            line-height: 24px;
            border-radius: 50%;
            background: rgba(255,255,255,0.18);
            text-align: center;
            font-size: 11px;
            font-weight: 800;
        }
        .section-band .title {
            font-size: 14px;
            font-weight: 700;
            letter-spacing: 0.02em;
            text-transform: uppercase;
        }
        .section-band .lead {
            margin-left: auto;
            font-size: 10px;
            color: rgba(255,255,255,0.7);
            text-transform: none;
            letter-spacing: 0;
            font-weight: 400;
        }
        .section-body {
            background: white;
            border: 1px solid #e5e7eb;
            border-top: none;
            border-radius: 0 0 10px 10px;
            padding: 20px 22px;
        }
        /* Strip away the inner section partials' own outer card chrome
           so we don't double-stack borders/rounded boxes. */
        .section-body > .bg-white {
            border: none !important;
            box-shadow: none !important;
            padding: 0 !important;
            margin: 0 !important;
        }
        .section-body > .bg-white + .grid {
            margin-top: 18px !important;
        }

        /* Footer + page-break behaviour ------------------------------- */
        .footer {
            margin-top: 18px;
            padding-top: 12px;
            border-top: 1px solid #d1d5db;
            display: flex;
            justify-content: space-between;
            font-size: 10px;
            color: #6b7280;
        }

        @media print {
            body { background: white !important; }
            .page { padding: 0; max-width: none; }
            .no-print { display: none !important; }
            .section-block { page-break-inside: avoid; break-inside: avoid; }
            .section-block { page-break-after: always; break-after: always; }
            .section-block:last-of-type { page-break-after: auto; break-after: auto; }
            .cover { page-break-after: always; break-after: always; }
            .toc  { page-break-after: always; break-after: always; }
        }
    </style>
</head>
<body class="text-gray-900">

<div class="page">

    {{-- Toolbar (hidden when printed) --}}
    <div class="no-print mb-4 flex items-center justify-end gap-2">
        <button onclick="window.print()" class="px-4 py-2 text-sm font-semibold bg-gray-900 text-white rounded-lg hover:bg-gray-800">
            Print
        </button>
        <button onclick="window.close()" class="px-4 py-2 text-sm font-semibold bg-white text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50">
            Close
        </button>
    </div>

    {{-- Cover --}}
    <div class="cover">
        <h2>Event Summary Report</h2>
        <h1>{{ $event->name }}</h1>
        <div class="meta">
            {{ $event->date?->format('l, F j, Y') }}
            @if($event->location)
                <span style="opacity: 0.6;"> · </span>{{ $event->location }}
            @endif
        </div>
        <div class="org-row">
            <div class="org-info">
                @if(! empty($branding['logo_src']))
                    <img src="{{ $branding['logo_src'] }}" alt="{{ $branding['app_name'] }}">
                @endif
                <div>
                    <div class="org-name">{{ $branding['app_name'] }}</div>
                    @if($orgEmail || $orgPhone || $orgWebsite)
                        <div class="org-contact">
                            @if($orgEmail) {{ $orgEmail }} @endif
                            @if($orgPhone) · {{ $orgPhone }} @endif
                            @if($orgWebsite) · {{ $orgWebsite }} @endif
                        </div>
                    @endif
                </div>
            </div>
            <div class="gen-info">
                Generated {{ now()->format('M j, Y · g:i A') }}<br>
                {{ count($sections) }} section{{ count($sections) === 1 ? '' : 's' }}
            </div>
        </div>
    </div>

    {{-- Table of contents --}}
    <div class="toc">
        <h3>In this report</h3>
        <ol>
            @foreach ($sections as $section)
                <li>{{ $sectionLabels[$section] ?? ucfirst($section) }}</li>
            @endforeach
        </ol>
    </div>

    {{-- Sections --}}
    @foreach ($sections as $idx => $section)
        <div class="section-block">
            <div class="section-band">
                <span class="num">{{ str_pad((string)($idx + 1), 2, '0', STR_PAD_LEFT) }}</span>
                <span class="title">{{ $sectionLabels[$section] ?? ucfirst($section) }}</span>
                <span class="lead">{{ $event->name }} · {{ $event->date?->format('M j, Y') }}</span>
            </div>
            <div class="section-body">
                @include('events.summary.sections._' . $section, [
                    'data'  => $data[$section] ?? null,
                    'event' => $event,
                ])
            </div>
        </div>
    @endforeach

    <div class="footer">
        <span>{{ $branding['app_name'] }} · Event Summary</span>
        <span>{{ $event->name }} · {{ $event->date?->format('M j, Y') }}</span>
    </div>
</div>

@if (! empty($autoPrint))
<script>
    // Wait a beat so layout fully paints before the print dialog fires.
    window.addEventListener('load', () => setTimeout(() => window.print(), 350));
</script>
@endif
</body>
</html>
