<?php

namespace App\Http\Controllers;

use App\Exceptions\VolunteerMergeConflictException;
use App\Http\Requests\StoreVolunteerRequest;
use App\Http\Requests\UpdateVolunteerRequest;
use App\Models\Volunteer;
use App\Models\VolunteerGroup;
use App\Services\VolunteerCheckInService;
use App\Services\VolunteerMergeService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\View\View;

class VolunteerController extends Controller
{
    public function __construct(
        protected VolunteerCheckInService $checkInService,
        protected VolunteerMergeService $mergeService,
    ) {}

    // ─── Index ────────────────────────────────────────────────────────────────

    public function index(Request $request): View
    {
        $this->authorize('viewAny', \App\Models\Volunteer::class);

        // events_served_count counts DISTINCT events, not check-in rows.
        // Two sessions on the same event day (check in, lunch, check back
        // in) is one event served — see VolunteerCheckInService::stats().
        // Subquery is portable across MySQL 8 + sqlite (no DISTINCT inside
        // withCount()). Index on volunteer_check_ins.volunteer_id (auto-
        // generated by foreignId()) keeps this cheap. The leading
        // select('volunteers.*') must come before selectSub() — selectSub
        // calls addSelect, but select() would replace.
        $query = Volunteer::select('volunteers.*')
            ->withCount('groups')
            ->selectSub(
                DB::table('volunteer_check_ins')
                    ->selectRaw('COUNT(DISTINCT event_id)')
                    ->whereColumn('volunteer_id', 'volunteers.id'),
                'events_served_count',
            );

        if ($search = $request->get('search')) {
            $query->search($search);
        }

        if ($role = $request->get('role')) {
            $query->where('role', $role);
        }

        // Group filter — only volunteers attached to this group_id.
        if ($groupId = $request->get('group')) {
            $query->whereHas('groups', fn ($q) => $q->where('volunteer_groups.id', $groupId));
        }

        $sort      = in_array($request->get('sort'), ['first_name', 'last_name', 'role', 'created_at'])
            ? $request->get('sort') : 'created_at';
        $direction = $request->get('direction') === 'asc' ? 'asc' : 'desc';

        $perPage = in_array((int) $request->get('per_page', 15), [15, 25, 50])
            ? (int) $request->get('per_page', 15) : 15;

        $volunteers = $query->orderBy($sort, $direction)
                            ->paginate($perPage)
                            ->withQueryString();

        $roles  = Volunteer::ROLES;
        // Light-weight list for the toolbar filter — name + id only.
        $groups = VolunteerGroup::orderBy('name')->get(['id', 'name']);

        return view('volunteers.index', compact('volunteers', 'roles', 'groups'));
    }

    // ─── Create ───────────────────────────────────────────────────────────────

    public function create(): View
    {
        $this->authorize('create', \App\Models\Volunteer::class);
        $roles = Volunteer::ROLES;
        return view('volunteers.create', compact('roles'));
    }

    // ─── Store ────────────────────────────────────────────────────────────────

    public function store(StoreVolunteerRequest $request): RedirectResponse
    {
        $this->authorize('create', \App\Models\Volunteer::class);
        $volunteer = Volunteer::create($request->validated());

        return redirect()
            ->route('volunteers.show', $volunteer)
            ->with('success', "Volunteer {$volunteer->full_name} created successfully.");
    }

    // ─── Show ─────────────────────────────────────────────────────────────────

    public function show(Volunteer $volunteer): View
    {
        $this->authorize('view', $volunteer);
        $volunteer->loadMissing('groups');
        $stats = $this->checkInService->stats($volunteer);

        // Groups the volunteer is NOT yet a member of — feeds the
        // "Add to group" quick-action picker on the Show page. Done as
        // a whereNotIn so the picker doesn't list groups they're
        // already in.
        $availableGroups = VolunteerGroup::whereNotIn('id', $volunteer->groups->pluck('id'))
            ->orderBy('name')
            ->get(['id', 'name']);

        // Phase 5.8 — candidate keepers for the Merge picker. Excludes
        // the current volunteer themselves; ordered by name for the
        // dropdown UX. Light-weight payload (id + names + phone).
        $mergeCandidates = Volunteer::where('id', '!=', $volunteer->id)
            ->orderBy('last_name')
            ->orderBy('first_name')
            ->get(['id', 'first_name', 'last_name', 'phone']);

        return view('volunteers.show', compact('volunteer', 'stats', 'availableGroups', 'mergeCandidates'));
    }

    // ─── Edit ─────────────────────────────────────────────────────────────────

    public function edit(Volunteer $volunteer): View
    {
        $this->authorize('update', $volunteer);
        $roles = Volunteer::ROLES;
        return view('volunteers.edit', compact('volunteer', 'roles'));
    }

    // ─── Update ───────────────────────────────────────────────────────────────

    public function update(UpdateVolunteerRequest $request, Volunteer $volunteer): RedirectResponse
    {
        $this->authorize('update', $volunteer);
        $volunteer->update($request->validated());

        return redirect()
            ->route('volunteers.show', $volunteer)
            ->with('success', 'Volunteer updated successfully.');
    }

    // ─── Destroy ──────────────────────────────────────────────────────────────

    public function destroy(Volunteer $volunteer): RedirectResponse
    {
        $this->authorize('delete', $volunteer);

        // Phase 5.6.f: volunteer_check_ins FK is restrictOnDelete now,
        // so deleting a volunteer with service history would blow up
        // with a SQLSTATE 23000 integrity violation. Pre-check and
        // surface a clear message instead — the count is informative,
        // and the admin can decide whether to clean up the rows first
        // or leave the volunteer record in place.
        $checkInCount = $volunteer->checkIns()->count();
        if ($checkInCount > 0) {
            return back()
                ->with('error', "{$volunteer->full_name} can't be removed — they have {$checkInCount} event check-in" . ($checkInCount === 1 ? '' : 's') . " on record. Archive instead, or contact an admin to clear the history.");
        }

        $name = $volunteer->full_name;
        $volunteer->delete();

        return redirect()
            ->route('volunteers.index')
            ->with('success', "{$name} has been removed.");
    }

    // ─── Attach to group (quick-add from Volunteer Show page) ────────────────

    /**
     * Attach this volunteer to a single group from the Show page picker.
     * Saves a navigation: previously had to leave the profile, open the
     * group, click Manage Members, find the volunteer, save.
     *
     * Authorized via VolunteerGroupPolicy::manageMembers (the same ability
     * gating the bulk member-sync UI), so any user with volunteers.edit
     * can attach.
     */
    public function attachGroup(Request $request, Volunteer $volunteer): RedirectResponse
    {
        $data = $request->validate([
            'group_id' => ['required', 'integer', Rule::exists('volunteer_groups', 'id')],
        ]);

        $group = VolunteerGroup::findOrFail($data['group_id']);
        $this->authorize('manageMembers', $group);

        // syncWithoutDetaching is idempotent — re-submitting the same
        // group_id (e.g. via stale form back-button) does not duplicate
        // the membership row. The pivot's UNIQUE(volunteer_id, group_id)
        // constraint backs this up at the DB level.
        $volunteer->groups()->syncWithoutDetaching([
            $group->id => ['joined_at' => now()],
        ]);

        return redirect()
            ->route('volunteers.show', $volunteer)
            ->with('success', "Added to group \"{$group->name}\".");
    }

    // ─── Merge into another volunteer (Phase 5.8) ────────────────────────────

    /**
     * Merge this volunteer (the "duplicate") into a chosen "keeper".
     *
     * Authorization: requires `volunteers.delete` (the duplicate row will
     * be deleted) AND `volunteers.edit` (the keeper row will be modified
     * via attached check-ins / memberships). Mirroring both ensures the
     * caller can perform every part of the merge.
     *
     * The atomic transfer is in VolunteerMergeService; this method is the
     * HTTP shim — it validates the keeper id, runs the service, and
     * surfaces VolunteerMergeConflictException as a friendly error
     * (same pattern as the HouseholdAlreadyServedException flow).
     */
    public function merge(Request $request, Volunteer $volunteer): RedirectResponse
    {
        $this->authorize('delete', $volunteer);

        $data = $request->validate([
            'keeper_id' => ['required', 'integer', 'exists:volunteers,id'],
        ]);

        // Laravel's `different:` rule references INPUT FIELDS, not route
        // bindings, so we can't express "different from the URL volunteer"
        // declaratively. Compare here so the validator surfaces the
        // session error in the same shape any other field rule would.
        if ((int) $data['keeper_id'] === $volunteer->id) {
            return back()
                ->withErrors(['keeper_id' => 'Cannot merge a volunteer with themselves.'])
                ->withInput();
        }

        $keeper = Volunteer::findOrFail($data['keeper_id']);
        $this->authorize('update', $keeper);

        try {
            $result = $this->mergeService->merge($keeper, $volunteer);
        } catch (VolunteerMergeConflictException $e) {
            $count = count($e->conflictingEventIds);
            return back()->with(
                'error',
                "Can't merge — both volunteers have open check-ins for {$count} event" . ($count === 1 ? '' : 's')
                . '. Please check them out first.',
            );
        }

        $checkIns = $result['check_ins_transferred'];
        $groups   = $result['groups_transferred'];
        $events   = $result['events_transferred'];

        return redirect()
            ->route('volunteers.show', $keeper)
            ->with(
                'success',
                "Merged \"{$result['merged_volunteer_name']}\" into \"{$keeper->full_name}\". "
                . "Transferred {$checkIns} check-in" . ($checkIns === 1 ? '' : 's')
                . ", {$groups} group" . ($groups === 1 ? '' : 's')
                . ", and {$events} event assignment" . ($events === 1 ? '' : 's') . '.',
            );
    }
}
